-- begin SPMU_CONTRACT_STAGE
alter table SPMU_CONTRACT_STAGE add constraint FK_SPMU_CONTRACT_STAGE_ON_CONTRACT foreign key (CONTRACT_ID) references SPMU_CONTRACT(ID)^
create index IDX_SPMU_CONTRACT_STAGE_ON_CONTRACT on SPMU_CONTRACT_STAGE (CONTRACT_ID)^
-- end SPMU_CONTRACT_STAGE
-- begin SPMU_APPLICATION_STAGE_VALUE
alter table SPMU_APPLICATION_STAGE_VALUE add constraint FK_SPMU_APPLICATION_STAGE_VALUE_ON_PLAN_ACCOUNT foreign key (PLAN_ACCOUNT_ID) references SPMU_PLAN_ACCOUNT(ID)^
alter table SPMU_APPLICATION_STAGE_VALUE add constraint FK_SPMU_APPLICATION_STAGE_VALUE_ON_ARTICLE foreign key (ARTICLE_ID) references SPMU_PLAN_ARTICLE(ID)^
alter table SPMU_APPLICATION_STAGE_VALUE add constraint FK_SPMU_APPLICATION_STAGE_VALUE_ON_ANALYTICA foreign key (ANALYTICA_ID) references SPMU_ACCOUNT(ID)^
alter table SPMU_APPLICATION_STAGE_VALUE add constraint FK_SPMU_APPLICATION_STAGE_VALUE_ON_MEASURE foreign key (MEASURE_ID) references SPMU_MEASURE(ID)^
alter table SPMU_APPLICATION_STAGE_VALUE add constraint FK_SPMU_APPLICATION_STAGE_VALUE_ON_APPLICATION_STAGE foreign key (APPLICATION_STAGE_ID) references SPMU_APPLICATION_STAGE(ID)^
alter table SPMU_APPLICATION_STAGE_VALUE add constraint FK_SPMU_APPLICATION_STAGE_VALUE_ON_PARENT foreign key (PARENT_ID) references SPMU_APPLICATION_STAGE_VALUE(ID)^
create index IDX_SPMU_APPLICATION_STAGE_VALUE_ON_PLAN_ACCOUNT on SPMU_APPLICATION_STAGE_VALUE (PLAN_ACCOUNT_ID)^
create index IDX_SPMU_APPLICATION_STAGE_VALUE_ON_ARTICLE on SPMU_APPLICATION_STAGE_VALUE (ARTICLE_ID)^
create index IDX_SPMU_APPLICATION_STAGE_VALUE_ON_ANALYTICA on SPMU_APPLICATION_STAGE_VALUE (ANALYTICA_ID)^
create index IDX_SPMU_APPLICATION_STAGE_VALUE_ON_MEASURE on SPMU_APPLICATION_STAGE_VALUE (MEASURE_ID)^
create index IDX_SPMU_APPLICATION_STAGE_VALUE_ON_APPLICATION_STAGE on SPMU_APPLICATION_STAGE_VALUE (APPLICATION_STAGE_ID)^
create index IDX_SPMU_APPLICATION_STAGE_VALUE_ON_PARENT on SPMU_APPLICATION_STAGE_VALUE (PARENT_ID)^
-- end SPMU_APPLICATION_STAGE_VALUE
-- begin SPMU_PLAN_ARTICLE
alter table SPMU_PLAN_ARTICLE add constraint FK_SPMU_PLAN_ARTICLE_ON_PARENT foreign key (PARENT_ID) references SPMU_PLAN_ARTICLE(ID)^
alter table SPMU_PLAN_ARTICLE add constraint FK_SPMU_PLAN_ARTICLE_ON_FINSOURCE foreign key (FINSOURCE_ID) references SPMU_FINSOURCE(ID)^
create index IDX_SPMU_PLAN_ARTICLE_ON_PARENT on SPMU_PLAN_ARTICLE (PARENT_ID)^
create index IDX_SPMU_PLAN_ARTICLE_ON_FINSOURCE on SPMU_PLAN_ARTICLE (FINSOURCE_ID)^
-- end SPMU_PLAN_ARTICLE
-- begin SPMU_AFFILATE
alter table SPMU_AFFILATE add constraint FK_SPMU_AFFILATE_ON_PARENT foreign key (PARENT_ID) references SPMU_AFFILATE(ID)^
create index IDX_SPMU_AFFILATE_ON_PARENT on SPMU_AFFILATE (PARENT_ID)^
-- end SPMU_AFFILATE
-- begin SPMU_PLAN_TYPE
alter table SPMU_PLAN_TYPE add constraint FK_SPMU_PLAN_TYPE_ON_FUNDING foreign key (FUNDING_ID) references SPMU_FINSOURCE(ID)^
alter table SPMU_PLAN_TYPE add constraint FK_SPMU_PLAN_TYPE_ON_CREATOR foreign key (CREATOR_ID) references SEC_USER(ID)^
create index IDX_SPMU_PLAN_TYPE_ON_FUNDING on SPMU_PLAN_TYPE (FUNDING_ID)^
create index IDX_SPMU_PLAN_TYPE_ON_CREATOR on SPMU_PLAN_TYPE (CREATOR_ID)^
-- end SPMU_PLAN_TYPE
-- begin SPMU_APPLICATION
alter table SPMU_APPLICATION add constraint FK_SPMU_APPLICATION_ON_AFFILIATE foreign key (AFFILIATE_ID) references SPMU_AFFILATE(ID)^
alter table SPMU_APPLICATION add constraint FK_SPMU_APPLICATION_ON_RESPONSIBLE foreign key (RESPONSIBLE_ID) references SPMU_EMPLOYEE(ID)^
alter table SPMU_APPLICATION add constraint FK_SPMU_APPLICATION_ON_TARGET foreign key (TARGET_ID) references SPMU_TARGET(ID)^
alter table SPMU_APPLICATION add constraint FK_SPMU_APPLICATION_ON_PLAN foreign key (PLAN_ID) references SPMU_PLAN_TYPE(ID)^
alter table SPMU_APPLICATION add constraint FK_SPMU_APPLICATION_ON_ARTICLE foreign key (ARTICLE_ID) references SPMU_PLAN_ARTICLE(ID)^
alter table SPMU_APPLICATION add constraint FK_SPMU_APPLICATION_ON_DIVISION foreign key (DIVISION_ID) references SPMU_DIVISION(ID)^
alter table SPMU_APPLICATION add constraint FK_SPMU_APPLICATION_ON_PLAN_ARTICLE foreign key (PLAN_ARTICLE_ID) references SPMU_PLAN_ARTICLE(ID)^
alter table SPMU_APPLICATION add constraint FK_SPMU_APPLICATION_ON_ANALYTICA foreign key (ANALYTICA_ID) references SPMU_ACCOUNT(ID)^
create index IDX_SPMU_APPLICATION_ON_AFFILIATE on SPMU_APPLICATION (AFFILIATE_ID)^
create index IDX_SPMU_APPLICATION_ON_RESPONSIBLE on SPMU_APPLICATION (RESPONSIBLE_ID)^
create index IDX_SPMU_APPLICATION_ON_TARGET on SPMU_APPLICATION (TARGET_ID)^
create index IDX_SPMU_APPLICATION_ON_PLAN on SPMU_APPLICATION (PLAN_ID)^
create index IDX_SPMU_APPLICATION_ON_ARTICLE on SPMU_APPLICATION (ARTICLE_ID)^
create index IDX_SPMU_APPLICATION_ON_DIVISION on SPMU_APPLICATION (DIVISION_ID)^
create index IDX_SPMU_APPLICATION_ON_PLAN_ARTICLE on SPMU_APPLICATION (PLAN_ARTICLE_ID)^
create index IDX_SPMU_APPLICATION_ON_ANALYTICA on SPMU_APPLICATION (ANALYTICA_ID)^
-- end SPMU_APPLICATION
-- begin SPMU_APPLICATION_STAGE_TYPE
alter table SPMU_APPLICATION_STAGE_TYPE add constraint FK_SPMU_APPLICATION_STAGE_TYPE_ON_CREATOR foreign key (CREATOR_ID) references SEC_USER(ID)^
create index IDX_SPMU_APPLICATION_STAGE_TYPE_ON_CREATOR on SPMU_APPLICATION_STAGE_TYPE (CREATOR_ID)^
-- end SPMU_APPLICATION_STAGE_TYPE
-- begin SPMU_COEFFICIENT_VALUE
alter table SPMU_COEFFICIENT_VALUE add constraint FK_SPMU_COEFFICIENT_VALUE_ON_COEFFICIENT foreign key (COEFFICIENT_ID) references SPMU_COEFFICIENT(ID)^
create index IDX_SPMU_COEFFICIENT_VALUE_ON_COEFFICIENT on SPMU_COEFFICIENT_VALUE (COEFFICIENT_ID)^
-- end SPMU_COEFFICIENT_VALUE
-- begin SPMU_APPLICATION_DETAIL_1
alter table SPMU_APPLICATION_DETAIL_1 add constraint FK_SPMU_APPLICATION_DETAIL_1_ON_APPLICATION foreign key (APPLICATION_ID) references SPMU_APPLICATION(ID)^
alter table SPMU_APPLICATION_DETAIL_1 add constraint FK_SPMU_APPLICATION_DETAIL_1_ON_TYPE foreign key (TYPE_ID) references SPMU_APPLICATION_DETAIL(ID)^
create index IDX_SPMU_APPLICATION_DETAIL_1_ON_APPLICATION on SPMU_APPLICATION_DETAIL_1 (APPLICATION_ID)^
create index IDX_SPMU_APPLICATION_DETAIL_1_ON_TYPE on SPMU_APPLICATION_DETAIL_1 (TYPE_ID)^
-- end SPMU_APPLICATION_DETAIL_1
-- begin SPMU_APPLICATION_FILE_DESCRIPTOR
alter table SPMU_APPLICATION_FILE_DESCRIPTOR add constraint FK_SPMU_APPLICATION_FILE_DESCRIPTOR_ON_APPLICATION foreign key (APPLICATION_ID) references SPMU_APPLICATION(ID)^
alter table SPMU_APPLICATION_FILE_DESCRIPTOR add constraint FK_SPMU_APPLICATION_FILE_DESCRIPTOR_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
create index IDX_SPMU_APPLICATION_FILE_DESCRIPTOR_ON_APPLICATION on SPMU_APPLICATION_FILE_DESCRIPTOR (APPLICATION_ID)^
create index IDX_SPMU_APPLICATION_FILE_DESCRIPTOR_ON_FILE on SPMU_APPLICATION_FILE_DESCRIPTOR (FILE_ID)^
-- end SPMU_APPLICATION_FILE_DESCRIPTOR
-- begin SPMU_REGISTRY_CONTENT
alter table SPMU_REGISTRY_CONTENT add constraint FK_SPMU_REGISTRY_CONTENT_ON_REGISTRY foreign key (REGISTRY_ID) references SPMU_REGISTRY(ID)^
alter table SPMU_REGISTRY_CONTENT add constraint FK_SPMU_REGISTRY_CONTENT_ON_APPLICATION foreign key (APPLICATION_ID) references SPMU_APPLICATION(ID)^
create index IDX_SPMU_REGISTRY_CONTENT_ON_REGISTRY on SPMU_REGISTRY_CONTENT (REGISTRY_ID)^
create index IDX_SPMU_REGISTRY_CONTENT_ON_APPLICATION on SPMU_REGISTRY_CONTENT (APPLICATION_ID)^
-- end SPMU_REGISTRY_CONTENT
-- begin SPMU_PLAN_SECTION
alter table SPMU_PLAN_SECTION add constraint FK_SPMU_PLAN_SECTION_ON_PARENT foreign key (PARENT_ID) references SPMU_PLAN_SECTION(ID)^
alter table SPMU_PLAN_SECTION add constraint FK_SPMU_PLAN_SECTION_ON_TYPE foreign key (TYPE_ID) references SPMU_PLAN_TYPE(ID)^
alter table SPMU_PLAN_SECTION add constraint FK_SPMU_PLAN_SECTION_ON_CREATOR foreign key (CREATOR_ID) references SEC_USER(ID)^
create index IDX_SPMU_PLAN_SECTION_ON_PARENT on SPMU_PLAN_SECTION (PARENT_ID)^
create index IDX_SPMU_PLAN_SECTION_ON_TYPE on SPMU_PLAN_SECTION (TYPE_ID)^
create index IDX_SPMU_PLAN_SECTION_ON_CREATOR on SPMU_PLAN_SECTION (CREATOR_ID)^
-- end SPMU_PLAN_SECTION
-- begin SPMU_EMPLOYEE
alter table SPMU_EMPLOYEE add constraint FK_SPMU_EMPLOYEE_ON_MANDATE foreign key (MANDATE_ID) references SPMU_MANDATE(ID)^
alter table SPMU_EMPLOYEE add constraint FK_SPMU_EMPLOYEE_ON_POSITION foreign key (POSITION_ID) references SPMU_POSITION(ID)^
create index IDX_SPMU_EMPLOYEE_ON_MANDATE on SPMU_EMPLOYEE (MANDATE_ID)^
create index IDX_SPMU_EMPLOYEE_ON_POSITION on SPMU_EMPLOYEE (POSITION_ID)^
-- end SPMU_EMPLOYEE
-- begin SPMU_APPLICATION_STAGE_CONTRACT
alter table SPMU_APPLICATION_STAGE_CONTRACT add constraint FK_SPMU_APPLICATION_STAGE_CONTRACT_ON_STAGE foreign key (STAGE_ID) references SPMU_APPLICATION_STAGE(ID)^
alter table SPMU_APPLICATION_STAGE_CONTRACT add constraint FK_SPMU_APPLICATION_STAGE_CONTRACT_ON_CONTRACT foreign key (CONTRACT_ID) references SPMU_CONTRACT_STAGE(ID)^
create index IDX_SPMU_APPLICATION_STAGE_CONTRACT_ON_STAGE on SPMU_APPLICATION_STAGE_CONTRACT (STAGE_ID)^
create index IDX_SPMU_APPLICATION_STAGE_CONTRACT_ON_CONTRACT on SPMU_APPLICATION_STAGE_CONTRACT (CONTRACT_ID)^
-- end SPMU_APPLICATION_STAGE_CONTRACT
-- begin SPMU_DIVISION
alter table SPMU_DIVISION add constraint FK_SPMU_DIVISION_ON_PARENT foreign key (PARENT_ID) references SPMU_DIVISION(ID)^
alter table SPMU_DIVISION add constraint FK_SPMU_DIVISION_ON_AFFILIATE foreign key (AFFILIATE_ID) references SPMU_AFFILATE(ID)^
create index IDX_SPMU_DIVISION_ON_PARENT on SPMU_DIVISION (PARENT_ID)^
create index IDX_SPMU_DIVISION_ON_AFFILIATE on SPMU_DIVISION (AFFILIATE_ID)^
-- end SPMU_DIVISION
-- begin SPMU_APPLICATION_LINK
alter table SPMU_APPLICATION_LINK add constraint FK_SPMU_APPLICATION_LINK_ON_PARENT foreign key (PARENT_ID) references SPMU_APPLICATION(ID)^
alter table SPMU_APPLICATION_LINK add constraint FK_SPMU_APPLICATION_LINK_ON_PARENT_STAGE foreign key (PARENT_STAGE_ID) references SPMU_APPLICATION_STAGE(ID)^
alter table SPMU_APPLICATION_LINK add constraint FK_SPMU_APPLICATION_LINK_ON_CHILD_STAGE foreign key (CHILD_STAGE_ID) references SPMU_APPLICATION_STAGE(ID)^
create index IDX_SPMU_APPLICATION_LINK_ON_PARENT on SPMU_APPLICATION_LINK (PARENT_ID)^
create index IDX_SPMU_APPLICATION_LINK_ON_PARENT_STAGE on SPMU_APPLICATION_LINK (PARENT_STAGE_ID)^
create index IDX_SPMU_APPLICATION_LINK_ON_CHILD_STAGE on SPMU_APPLICATION_LINK (CHILD_STAGE_ID)^
-- end SPMU_APPLICATION_LINK
-- begin SPMU_COEFFICIENT
alter table SPMU_COEFFICIENT add constraint FK_SPMU_COEFFICIENT_ON_MEASURE foreign key (MEASURE_ID) references SPMU_MEASURE(ID)^
create index IDX_SPMU_COEFFICIENT_ON_MEASURE on SPMU_COEFFICIENT (MEASURE_ID)^
-- end SPMU_COEFFICIENT
-- begin SPMU_ANO
alter table SPMU_ANO add constraint FK_SPMU_ANO_ON_AFFILIATE foreign key (AFFILIATE_ID) references SPMU_AFFILATE(ID)^
alter table SPMU_ANO add constraint FK_SPMU_ANO_ON_FLIGHT_TYPE foreign key (FLIGHT_TYPE_ID) references SPMU_FLYGHT_TYPE(ID)^
create index IDX_SPMU_ANO_ON_AFFILIATE on SPMU_ANO (AFFILIATE_ID)^
create index IDX_SPMU_ANO_ON_FLIGHT_TYPE on SPMU_ANO (FLIGHT_TYPE_ID)^
-- end SPMU_ANO
-- begin SPMU_PLAN_ACCOUNT
alter table SPMU_PLAN_ACCOUNT add constraint FK_SPMU_PLAN_ACCOUNT_ON_ARTICLE foreign key (ARTICLE_ID) references SPMU_PLAN_ARTICLE(ID)^
create index IDX_SPMU_PLAN_ACCOUNT_ON_ARTICLE on SPMU_PLAN_ACCOUNT (ARTICLE_ID)^
-- end SPMU_PLAN_ACCOUNT
-- begin SPMU_APPLICATION_OBJECT_TYPE
alter table SPMU_APPLICATION_OBJECT_TYPE add constraint FK_SPMU_APPLICATION_OBJECT_TYPE_ON_PARENT foreign key (PARENT_ID) references SPMU_APPLICATION_OBJECT_TYPE(ID)^
create index IDX_SPMU_APPLICATION_OBJECT_TYPE_ON_PARENT on SPMU_APPLICATION_OBJECT_TYPE (PARENT_ID)^
-- end SPMU_APPLICATION_OBJECT_TYPE
-- begin SPMU_WORKFLOW
alter table SPMU_WORKFLOW add constraint FK_SPMU_WORKFLOW_ON_PARENT foreign key (PARENT_ID) references SPMU_WORKFLOW(ID)^
create index IDX_SPMU_WORKFLOW_ON_PARENT on SPMU_WORKFLOW (PARENT_ID)^
-- end SPMU_WORKFLOW

-- begin SPMU_APPLICATION_STAGE
alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_PARENT foreign key (PARENT_ID) references SPMU_APPLICATION_STAGE(ID)^
alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_AFFILIATE foreign key (AFFILIATE_ID) references SPMU_AFFILATE(ID)^
alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_OBJECT foreign key (OBJECT_ID) references SPMU_APPLICATION_OBJECT(ID)^
alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_TYPE foreign key (TYPE_ID) references SPMU_APPLICATION_STAGE_TYPE(ID)^
alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_PLAN foreign key (PLAN_ID) references SPMU_PLAN_TYPE(ID)^
alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_SECTION foreign key (SECTION_ID) references SPMU_PLAN_SECTION(ID)^
alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_APPLICATION foreign key (APPLICATION_ID) references SPMU_APPLICATION(ID)^
alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_PLAN_ARTICLE foreign key (PLAN_ARTICLE_ID) references SPMU_PLAN_ARTICLE(ID)^
alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_ANALYTICA foreign key (ANALYTICA_ID) references SPMU_ACCOUNT(ID)^
alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_FIXED_ASSET foreign key (FIXED_ASSET_ID) references SPMU_FIXED_ASSET(ID)^
alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_LOCATION foreign key (LOCATION_ID) references SPMU_LOCATION(ID)^
alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_EQUIPMENT_OBJECT foreign key (EQUIPMENT_OBJECT_ID) references SPMU_EQUIPMENT_OBJECT(ID)^
alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_PRIORITY foreign key (PRIORITY_ID) references SPMU_PRIORITY(ID)^
alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_PRICING_PROCEDURE foreign key (PRICING_PROCEDURE_ID) references SPMU_PRICING_PROCEDURE(ID)^
create index IDX_SPMU_APPLICATION_STAGE_ON_PARENT on SPMU_APPLICATION_STAGE (PARENT_ID)^
create index IDX_SPMU_APPLICATION_STAGE_ON_AFFILIATE on SPMU_APPLICATION_STAGE (AFFILIATE_ID)^
create index IDX_SPMU_APPLICATION_STAGE_ON_OBJECT on SPMU_APPLICATION_STAGE (OBJECT_ID)^
create index IDX_SPMU_APPLICATION_STAGE_ON_TYPE on SPMU_APPLICATION_STAGE (TYPE_ID)^
create index IDX_SPMU_APPLICATION_STAGE_ON_PLAN on SPMU_APPLICATION_STAGE (PLAN_ID)^
create index IDX_SPMU_APPLICATION_STAGE_ON_SECTION on SPMU_APPLICATION_STAGE (SECTION_ID)^
create index IDX_SPMU_APPLICATION_STAGE_ON_APPLICATION on SPMU_APPLICATION_STAGE (APPLICATION_ID)^
create index IDX_SPMU_APPLICATION_STAGE_ON_PLAN_ARTICLE on SPMU_APPLICATION_STAGE (PLAN_ARTICLE_ID)^
create index IDX_SPMU_APPLICATION_STAGE_ON_ANALYTICA on SPMU_APPLICATION_STAGE (ANALYTICA_ID)^
create index IDX_SPMU_APPLICATION_STAGE_ON_FIXED_ASSET on SPMU_APPLICATION_STAGE (FIXED_ASSET_ID)^
create index IDX_SPMU_APPLICATION_STAGE_ON_LOCATION on SPMU_APPLICATION_STAGE (LOCATION_ID)^
create index IDX_SPMU_APPLICATION_STAGE_ON_EQUIPMENT_OBJECT on SPMU_APPLICATION_STAGE (EQUIPMENT_OBJECT_ID)^
create index IDX_SPMU_APPLICATION_STAGE_ON_PRIORITY on SPMU_APPLICATION_STAGE (PRIORITY_ID)^
create index IDX_SPMU_APPLICATION_STAGE_ON_PRICING_PROCEDURE on SPMU_APPLICATION_STAGE (PRICING_PROCEDURE_ID)^
-- end SPMU_APPLICATION_STAGE
-- begin SPMU_APPLICATION_OBJECT_STAGE
alter table SPMU_APPLICATION_OBJECT_STAGE add constraint FK_SPMU_APPLICATION_OBJECT_STAGE_ON_OBJECT foreign key (OBJECT_ID) references SPMU_APPLICATION_OBJECT(ID)^
alter table SPMU_APPLICATION_OBJECT_STAGE add constraint FK_SPMU_APPLICATION_OBJECT_STAGE_ON_STAGE foreign key (STAGE_ID) references SPMU_APPLICATION_STAGE(ID)^
create index IDX_SPMU_APPLICATION_OBJECT_STAGE_ON_OBJECT on SPMU_APPLICATION_OBJECT_STAGE (OBJECT_ID)^
create index IDX_SPMU_APPLICATION_OBJECT_STAGE_ON_STAGE on SPMU_APPLICATION_OBJECT_STAGE (STAGE_ID)^
-- end SPMU_APPLICATION_OBJECT_STAGE
-- begin SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR
alter table SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR add constraint FK_SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR_ON_APPLICATION foreign key (APPLICATION_ID) references SPMU_APPLICATION_STAGE(ID)^
alter table SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR add constraint FK_SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
create index IDX_SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR_ON_APPLICATION on SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR (APPLICATION_ID)^
create index IDX_SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR_ON_FILE on SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR (FILE_ID)^
-- end SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR
-- begin SPMU_APPLICATION_OBJECT
alter table SPMU_APPLICATION_OBJECT add constraint FK_SPMU_APPLICATION_OBJECT_ON_ORIGIN foreign key (ORIGIN_ID) references SPMU_APPLICATION_OBJECT(ID)^
alter table SPMU_APPLICATION_OBJECT add constraint FK_SPMU_APPLICATION_OBJECT_ON_PARENT foreign key (PARENT_ID) references SPMU_APPLICATION_OBJECT(ID)^
alter table SPMU_APPLICATION_OBJECT add constraint FK_SPMU_APPLICATION_OBJECT_ON_AFFILIATE foreign key (AFFILIATE_ID) references SPMU_AFFILATE(ID)^
alter table SPMU_APPLICATION_OBJECT add constraint FK_SPMU_APPLICATION_OBJECT_ON_DIVISION foreign key (DIVISION_ID) references SPMU_DIVISION(ID)^
alter table SPMU_APPLICATION_OBJECT add constraint FK_SPMU_APPLICATION_OBJECT_ON_TYPE foreign key (TYPE_ID) references SPMU_APPLICATION_OBJECT_TYPE(ID)^
create index IDX_SPMU_APPLICATION_OBJECT_ON_ORIGIN on SPMU_APPLICATION_OBJECT (ORIGIN_ID)^
create index IDX_SPMU_APPLICATION_OBJECT_ON_PARENT on SPMU_APPLICATION_OBJECT (PARENT_ID)^
create index IDX_SPMU_APPLICATION_OBJECT_ON_AFFILIATE on SPMU_APPLICATION_OBJECT (AFFILIATE_ID)^
create index IDX_SPMU_APPLICATION_OBJECT_ON_DIVISION on SPMU_APPLICATION_OBJECT (DIVISION_ID)^
create index IDX_SPMU_APPLICATION_OBJECT_ON_TYPE on SPMU_APPLICATION_OBJECT (TYPE_ID)^
-- end SPMU_APPLICATION_OBJECT
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_ON_AFFILIATE foreign key (AFFILIATE_ID) references SPMU_AFFILATE(ID)^
create index IDX_SEC_USER_ON_AFFILIATE on SEC_USER (AFFILIATE_ID)^
alter table SEC_USER add constraint FK_SEC_USER_ON_MANDATE foreign key (MANDATE_ID) references SPMU_MANDATE(ID)^
create index IDX_SEC_USER_ON_MANDATE on SEC_USER (MANDATE_ID)^
alter table SEC_USER add constraint FK_SEC_USER_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references SPMU_EMPLOYEE(ID)^
create index IDX_SEC_USER_ON_EMPLOYEE on SEC_USER (EMPLOYEE_ID)^
-- end SEC_USER
-- begin SPMU_APPLICATION_HISTORY
alter table SPMU_APPLICATION_HISTORY add constraint FK_SPMU_APPLICATION_HISTORY_ON_ENTITY_SNAPSHOT foreign key (ENTITY_SNAPSHOT_ID) references SYS_ENTITY_SNAPSHOT(ID)^
alter table SPMU_APPLICATION_HISTORY add constraint FK_SPMU_APPLICATION_HISTORY_ON_PROC_TASK foreign key (PROC_TASK_ID) references BPM_PROC_TASK(ID)^
alter table SPMU_APPLICATION_HISTORY add constraint FK_SPMU_APPLICATION_HISTORY_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_SPMU_APPLICATION_HISTORY_ON_ENTITY_SNAPSHOT on SPMU_APPLICATION_HISTORY (ENTITY_SNAPSHOT_ID)^
create index IDX_SPMU_APPLICATION_HISTORY_ON_PROC_TASK on SPMU_APPLICATION_HISTORY (PROC_TASK_ID)^
create index IDX_SPMU_APPLICATION_HISTORY_ON_USER on SPMU_APPLICATION_HISTORY (USER_ID)^
-- end SPMU_APPLICATION_HISTORY
-- begin SPMU_APPLICATION_RESPONSIBLE
alter table SPMU_APPLICATION_RESPONSIBLE add constraint FK_SPMU_APPLICATION_RESPONSIBLE_ON_APPLICATION foreign key (APPLICATION_ID) references SPMU_APPLICATION(ID)^
alter table SPMU_APPLICATION_RESPONSIBLE add constraint FK_SPMU_APPLICATION_RESPONSIBLE_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references SPMU_EMPLOYEE(ID)^
create index IDX_SPMU_APPLICATION_RESPONSIBLE_ON_APPLICATION on SPMU_APPLICATION_RESPONSIBLE (APPLICATION_ID)^
create index IDX_SPMU_APPLICATION_RESPONSIBLE_ON_EMPLOYEE on SPMU_APPLICATION_RESPONSIBLE (EMPLOYEE_ID)^
-- end SPMU_APPLICATION_RESPONSIBLE
-- begin SPMU_APPLICATION_STAGE_RESPONSIBLE
alter table SPMU_APPLICATION_STAGE_RESPONSIBLE add constraint FK_SPMU_APPLICATION_STAGE_RESPONSIBLE_ON_APPLICATIONSTAGE foreign key (APPLICATIONSTAGE_ID) references SPMU_APPLICATION_STAGE(ID)^
alter table SPMU_APPLICATION_STAGE_RESPONSIBLE add constraint FK_SPMU_APPLICATION_STAGE_RESPONSIBLE_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references SPMU_EMPLOYEE(ID)^
create index IDX_SPMU_APPLICATION_STAGE_RESPONSIBLE_ON_APPLICATIONSTAGE on SPMU_APPLICATION_STAGE_RESPONSIBLE (APPLICATIONSTAGE_ID)^
create index IDX_SPMU_APPLICATION_STAGE_RESPONSIBLE_ON_EMPLOYEE on SPMU_APPLICATION_STAGE_RESPONSIBLE (EMPLOYEE_ID)^
-- end SPMU_APPLICATION_STAGE_RESPONSIBLE
-- begin SPMU_APPLICATION_LINK
--alter table SPMU_APPLICATION_LINK add constraint FK_SPMU_APPLICATION_LINK_ON_PARENT foreign key (PARENT_ID) references SPMU_APPLICATION(ID)^
--alter table SPMU_APPLICATION_LINK add constraint FK_SPMU_APPLICATION_LINK_ON_CHILD foreign key (CHILD_ID) references SPMU_APPLICATION(ID)^
--alter table SPMU_APPLICATION_LINK add constraint FK_SPMU_APPLICATION_LINK_ON_CHILD_STAGE foreign key (CHILD_STAGE_ID) references SPMU_APPLICATION_STAGE(ID)^
--create index IDX_SPMU_APPLICATION_LINK_ON_PARENT on SPMU_APPLICATION_LINK (PARENT_ID)^
--create index IDX_SPMU_APPLICATION_LINK_ON_CHILD on SPMU_APPLICATION_LINK (CHILD_ID)^
--create index IDX_SPMU_APPLICATION_LINK_ON_CHILD_STAGE on SPMU_APPLICATION_LINK (CHILD_STAGE_ID)^
-- end SPMU_APPLICATION_LINK
-- begin SPMU_APPLICATION_STAGE_LINK
--alter table SPMU_APPLICATION_STAGE_LINK add constraint FK_SPMU_APPLICATION_STAGE_LINK_ON_PARENT foreign key (PARENT_ID) references SPMU_APPLICATION_STAGE(ID)^
--alter table SPMU_APPLICATION_STAGE_LINK add constraint FK_SPMU_APPLICATION_STAGE_LINK_ON_CHILD foreign key (CHILD_ID) references SPMU_APPLICATION(ID)^
--alter table SPMU_APPLICATION_STAGE_LINK add constraint FK_SPMU_APPLICATION_STAGE_LINK_ON_CHILD_STAGE foreign key (CHILD_STAGE_ID) references SPMU_APPLICATION_STAGE(ID)^
--create index IDX_SPMU_APPLICATION_STAGE_LINK_ON_PARENT on SPMU_APPLICATION_STAGE_LINK (PARENT_ID)^
--create index IDX_SPMU_APPLICATION_STAGE_LINK_ON_CHILD on SPMU_APPLICATION_STAGE_LINK (CHILD_ID)^
--create index IDX_SPMU_APPLICATION_STAGE_LINK_ON_CHILD_STAGE on SPMU_APPLICATION_STAGE_LINK (CHILD_STAGE_ID)^
-- end SPMU_APPLICATION_STAGE_LINK
-- begin SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR
--alter table SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR add constraint FK_SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR_ON_APPLICATION foreign key (APPLICATION_ID) references SPMU_APPLICATION_STAGE(ID)^
--alter table SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR add constraint FK_SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
--create index IDX_SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR_ON_APPLICATION on SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR (APPLICATION_ID)^
--create index IDX_SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR_ON_FILE on SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR (FILE_ID)^
-- end SPMU_APPLICATION_STAGE_FILE_DESCRIPTOR
-- begin SPMU_APPLICATION_FILE_DESCRIPTOR
--alter table SPMU_APPLICATION_FILE_DESCRIPTOR add constraint FK_SPMU_APPLICATION_FILE_DESCRIPTOR_ON_APPLICATION foreign key (APPLICATION_ID) references SPMU_APPLICATION(ID)^
--alter table SPMU_APPLICATION_FILE_DESCRIPTOR add constraint FK_SPMU_APPLICATION_FILE_DESCRIPTOR_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
--create index IDX_SPMU_APPLICATION_FILE_DESCRIPTOR_ON_APPLICATION on SPMU_APPLICATION_FILE_DESCRIPTOR (APPLICATION_ID)^
--create index IDX_SPMU_APPLICATION_FILE_DESCRIPTOR_ON_FILE on SPMU_APPLICATION_FILE_DESCRIPTOR (FILE_ID)^
-- end SPMU_APPLICATION_FILE_DESCRIPTOR
-- begin SPMU_FIXED_ASSET
alter table SPMU_FIXED_ASSET add constraint FK_SPMU_FIXED_ASSET_ON_PARENT foreign key (PARENT_ID) references SPMU_FIXED_ASSET(ID)^
create index IDX_SPMU_FIXED_ASSET_ON_PARENT on SPMU_FIXED_ASSET (PARENT_ID)^
-- end SPMU_FIXED_ASSET
-- begin SPMU_EQUIPMENT_OBJECT
alter table SPMU_EQUIPMENT_OBJECT add constraint FK_SPMU_EQUIPMENT_OBJECT_ON_PARENT foreign key (PARENT_ID) references SPMU_EQUIPMENT_OBJECT(ID)^
alter table SPMU_EQUIPMENT_OBJECT add constraint FK_SPMU_EQUIPMENT_OBJECT_ON_AFFILATE foreign key (AFFILATE_ID) references SPMU_AFFILATE(ID)^
alter table SPMU_EQUIPMENT_OBJECT add constraint FK_SPMU_EQUIPMENT_OBJECT_ON_DIVISION foreign key (DIVISION_ID) references SPMU_DIVISION(ID)^
alter table SPMU_EQUIPMENT_OBJECT add constraint FK_SPMU_EQUIPMENT_OBJECT_ON_LOCATION foreign key (LOCATION_ID) references SPMU_LOCATION(ID)^
create index IDX_SPMU_EQUIPMENT_OBJECT_ON_PARENT on SPMU_EQUIPMENT_OBJECT (PARENT_ID)^
create index IDX_SPMU_EQUIPMENT_OBJECT_ON_AFFILATE on SPMU_EQUIPMENT_OBJECT (AFFILATE_ID)^
create index IDX_SPMU_EQUIPMENT_OBJECT_ON_DIVISION on SPMU_EQUIPMENT_OBJECT (DIVISION_ID)^
create index IDX_SPMU_EQUIPMENT_OBJECT_ON_LOCATION on SPMU_EQUIPMENT_OBJECT (LOCATION_ID)^
-- end SPMU_EQUIPMENT_OBJECT
-- begin SPMU_PLAN_ARTICLE_STAGE
alter table SPMU_PLAN_ARTICLE_STAGE add constraint FK_SPMU_PLAN_ARTICLE_STAGE_ON_PLAN_ARTICLE foreign key (PLAN_ARTICLE_ID) references SPMU_PLAN_ARTICLE(ID)^
create index IDX_SPMU_PLAN_ARTICLE_STAGE_ON_PLAN_ARTICLE on SPMU_PLAN_ARTICLE_STAGE (PLAN_ARTICLE_ID)^
-- end SPMU_PLAN_ARTICLE_STAGE
-- begin SPMU_PLAN_VARIANT
alter table SPMU_PLAN_VARIANT add constraint FK_SPMU_PLAN_VARIANT_ON_RESPONSIBLE foreign key (RESPONSIBLE_ID) references SPMU_EMPLOYEE(ID)^
create index IDX_SPMU_PLAN_VARIANT_ON_RESPONSIBLE on SPMU_PLAN_VARIANT (RESPONSIBLE_ID)^
-- end SPMU_PLAN_VARIANT
-- begin SPMU_PLAN_VARIANT_LIMIT
alter table SPMU_PLAN_VARIANT_LIMIT add constraint FK_SPMU_PLAN_VARIANT_LIMIT_ON_PLAN_VARIANT foreign key (PLAN_VARIANT_ID) references SPMU_PLAN_VARIANT(ID)^
create index IDX_SPMU_PLAN_VARIANT_LIMIT_ON_PLAN_VARIANT on SPMU_PLAN_VARIANT_LIMIT (PLAN_VARIANT_ID)^
-- end SPMU_PLAN_VARIANT_LIMIT
-- begin SPMU_PLAN_VARIANT_TEMPLATE
alter table SPMU_PLAN_VARIANT_TEMPLATE add constraint FK_SPMU_PLAN_VARIANT_TEMPLATE_ON_PLAN_VARIANT foreign key (PLAN_VARIANT_ID) references SPMU_PLAN_VARIANT(ID)^
create index IDX_SPMU_PLAN_VARIANT_TEMPLATE_ON_PLAN_VARIANT on SPMU_PLAN_VARIANT_TEMPLATE (PLAN_VARIANT_ID)^
-- end SPMU_PLAN_VARIANT_TEMPLATE
-- begin SPMU_PLAN_VARIANT_FILTER
alter table SPMU_PLAN_VARIANT_FILTER add constraint FK_SPMU_PLAN_VARIANT_FILTER_ON_PLAN_VARIANT_TEMPLATE foreign key (PLAN_VARIANT_TEMPLATE_ID) references SPMU_PLAN_VARIANT_TEMPLATE(ID)^
alter table SPMU_PLAN_VARIANT_FILTER add constraint FK_SPMU_PLAN_VARIANT_FILTER_ON_FILTER foreign key (FILTER_ID) references SEC_FILTER(ID)^
create index IDX_SPMU_PLAN_VARIANT_FILTER_ON_PLAN_VARIANT_TEMPLATE on SPMU_PLAN_VARIANT_FILTER (PLAN_VARIANT_TEMPLATE_ID)^
create index IDX_SPMU_PLAN_VARIANT_FILTER_ON_FILTER on SPMU_PLAN_VARIANT_FILTER (FILTER_ID)^
-- end SPMU_PLAN_VARIANT_FILTER
-- begin SPMU_PLAN_VARIANT_TEMPLATE_APPLICATION
alter table SPMU_PLAN_VARIANT_TEMPLATE_APPLICATION add constraint FK_SPMU_PLAN_VARIANT_TEMPLATE_APPLICATION_ON_PLAN_VARIANT_TEMPLATE foreign key (PLAN_VARIANT_TEMPLATE_ID) references SPMU_PLAN_VARIANT_TEMPLATE(ID)^
alter table SPMU_PLAN_VARIANT_TEMPLATE_APPLICATION add constraint FK_SPMU_PLAN_VARIANT_TEMPLATE_APPLICATION_ON_APPLICATION_TEMPLATE foreign key (APPLICATION_TEMPLATE_ID) references SPMU_APPLICATION(ID)^
create index IDX_SPMU_PLAN_VARIANT_TEMPLATE_APPLICATION_ON_PLAN_VARIANT_TEMPLATE on SPMU_PLAN_VARIANT_TEMPLATE_APPLICATION (PLAN_VARIANT_TEMPLATE_ID)^
create index IDX_SPMU_PLAN_VARIANT_TEMPLATE_APPLICATION_ON_APPLICATION_TEMPLATE on SPMU_PLAN_VARIANT_TEMPLATE_APPLICATION (APPLICATION_TEMPLATE_ID)^
-- end SPMU_PLAN_VARIANT_TEMPLATE_APPLICATION
-- begin SPMU_PLAN_VARIANT_TEMPLATE_ELEMENT
alter table SPMU_PLAN_VARIANT_TEMPLATE_ELEMENT add constraint FK_SPMU_PLAN_VARIANT_TEMPLATE_ELEMENT_ON_PLAN_VARIANT_TEMPLATE foreign key (PLAN_VARIANT_TEMPLATE_ID) references SPMU_PLAN_VARIANT_TEMPLATE(ID)^
create index IDX_SPMU_PLAN_VARIANT_TEMPLATE_ELEMENT_ON_PLAN_VARIANT_TEMPLATE on SPMU_PLAN_VARIANT_TEMPLATE_ELEMENT (PLAN_VARIANT_TEMPLATE_ID)^
-- end SPMU_PLAN_VARIANT_TEMPLATE_ELEMENT
-- begin SPMU_STATIC_VARIABLE
alter table SPMU_STATIC_VARIABLE add constraint FK_SPMU_STATIC_VARIABLE_ON_COMPUTED_VARIABLE foreign key (COMPUTED_VARIABLE_ID) references SPMU_COMPUTED_VARIABLE(ID)^
create index IDX_SPMU_STATIC_VARIABLE_ON_COMPUTED_VARIABLE on SPMU_STATIC_VARIABLE (COMPUTED_VARIABLE_ID)^
-- end SPMU_STATIC_VARIABLE
-- begin SPMU_ENTITY_VARIABLE
alter table SPMU_ENTITY_VARIABLE add constraint FK_SPMU_ENTITY_VARIABLE_ON_COMPUTED_VARIABLE foreign key (COMPUTED_VARIABLE_ID) references SPMU_COMPUTED_VARIABLE(ID)^
create index IDX_SPMU_ENTITY_VARIABLE_ON_COMPUTED_VARIABLE on SPMU_ENTITY_VARIABLE (COMPUTED_VARIABLE_ID)^
-- end SPMU_ENTITY_VARIABLE
-- begin SPMU_COMPUTED_VARIABLE
alter table SPMU_COMPUTED_VARIABLE add constraint FK_SPMU_COMPUTED_VARIABLE_ON_PLAN_VARIANT_TEMPLATE foreign key (PLAN_VARIANT_TEMPLATE_ID) references SPMU_PLAN_VARIANT_TEMPLATE(ID)^
create index IDX_SPMU_COMPUTED_VARIABLE_ON_PLAN_VARIANT_TEMPLATE on SPMU_COMPUTED_VARIABLE (PLAN_VARIANT_TEMPLATE_ID)^
-- end SPMU_COMPUTED_VARIABLE
-- begin SPMU_ENUM_VARIABLE
alter table SPMU_ENUM_VARIABLE add constraint FK_SPMU_ENUM_VARIABLE_ON_COMPUTED_VARIABLE foreign key (COMPUTED_VARIABLE_ID) references SPMU_COMPUTED_VARIABLE(ID)^
create index IDX_SPMU_ENUM_VARIABLE_ON_COMPUTED_VARIABLE on SPMU_ENUM_VARIABLE (COMPUTED_VARIABLE_ID)^
-- end SPMU_ENUM_VARIABLE
-- begin SPMU_COMPUTED_VARIABLE_LINK
alter table SPMU_COMPUTED_VARIABLE_LINK add constraint FK_SPMU_COMPUTED_VARIABLE_LINK_ON_COMPUTED_VARIABLE foreign key (COMPUTED_VARIABLE_ID) references SPMU_COMPUTED_VARIABLE(ID)^
alter table SPMU_COMPUTED_VARIABLE_LINK add constraint FK_SPMU_COMPUTED_VARIABLE_LINK_ON_COMPUTED_VARIABLE_CHILD foreign key (COMPUTED_VARIABLE_CHILD_ID) references SPMU_COMPUTED_VARIABLE(ID)^
create index IDX_SPMU_COMPUTED_VARIABLE_LINK_ON_COMPUTED_VARIABLE on SPMU_COMPUTED_VARIABLE_LINK (COMPUTED_VARIABLE_ID)^
create index IDX_SPMU_COMPUTED_VARIABLE_LINK_ON_COMPUTED_VARIABLE_CHILD on SPMU_COMPUTED_VARIABLE_LINK (COMPUTED_VARIABLE_CHILD_ID)^
-- end SPMU_COMPUTED_VARIABLE_LINK
