alter table SPMU_DIVISION add constraint FK_SPMU_DIVISION_ON_PARENT foreign key (PARENT_ID) references SPMU_DIVISION(ID);
alter table SPMU_DIVISION add constraint FK_SPMU_DIVISION_ON_AFFILIATE foreign key (AFFILIATE_ID) references SPMU_AFFILATE(ID);
create index IDX_SPMU_DIVISION_ON_PARENT on SPMU_DIVISION (PARENT_ID);
create index IDX_SPMU_DIVISION_ON_AFFILIATE on SPMU_DIVISION (AFFILIATE_ID);
