alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_AFFILIATE foreign key (AFFILIATE_ID) references SPMU_AFFILATE(ID);
create index IDX_SPMU_APPLICATION_STAGE_ON_AFFILIATE on SPMU_APPLICATION_STAGE (AFFILIATE_ID);
