alter table SPMU_APPLICATION_STAGE_TYPE add constraint FK_SPMU_APPLICATION_STAGE_TYPE_ON_CREATOR foreign key (CREATOR_ID) references SEC_USER(ID);
create index IDX_SPMU_APPLICATION_STAGE_TYPE_ON_CREATOR on SPMU_APPLICATION_STAGE_TYPE (CREATOR_ID);
