alter table SPMU_PLAN_ARTICLE add constraint FK_SPMU_PLAN_ARTICLE_ON_PARENT foreign key (PARENT_ID) references SPMU_PLAN_ARTICLE(ID);
alter table SPMU_PLAN_ARTICLE add constraint FK_SPMU_PLAN_ARTICLE_ON_FINSOURCE foreign key (FINSOURCE_ID) references SPMU_FINSOURCE(ID);
create index IDX_SPMU_PLAN_ARTICLE_ON_PARENT on SPMU_PLAN_ARTICLE (PARENT_ID);
create index IDX_SPMU_PLAN_ARTICLE_ON_FINSOURCE on SPMU_PLAN_ARTICLE (FINSOURCE_ID);
