alter table SPMU_PLAN_ACCOUNT add constraint FK_SPMU_PLAN_ACCOUNT_ON_ARTICLE foreign key (ARTICLE_ID) references SPMU_PLAN_ARTICLE(ID);
create index IDX_SPMU_PLAN_ACCOUNT_ON_ARTICLE on SPMU_PLAN_ACCOUNT (ARTICLE_ID);
