exec sp_rename 'SPMU_APPLICATION_STAGE_CONTRACT.STAGE_ID', 'STAGE_ID__U03330', 'COLUMN' ^
alter table SPMU_APPLICATION_STAGE_CONTRACT alter column STAGE_ID__U03330 uniqueidentifier  ;
drop index IDX_SPMU_APPLICATION_STAGE_CONTRACT_ON_STAGE on SPMU_APPLICATION_STAGE_CONTRACT ;
alter table SPMU_APPLICATION_STAGE_CONTRACT drop constraint FK_SPMU_APPLICATION_STAGE_CONTRACT_ON_STAGE ;
