exec sp_rename 'SPMU_APPLICATION_STAGE_VALUE.APPLICATION_STAGE_ID', 'APPLICATION_STAGE_ID__U02950', 'COLUMN' ^
drop index IDX_SPMU_APPLICATION_STAGE_VALUE_ON_APPLICATION_STAGE on SPMU_APPLICATION_STAGE_VALUE ;
alter table SPMU_APPLICATION_STAGE_VALUE drop constraint FK_SPMU_APPLICATION_STAGE_VALUE_ON_APPLICATION_STAGE ;
-- alter table SPMU_APPLICATION_STAGE_VALUE add STAGE_ID uniqueidentifier ^
-- update SPMU_APPLICATION_STAGE_VALUE set STAGE_ID = <default_value> ;
-- alter table SPMU_APPLICATION_STAGE_VALUE alter column STAGE_ID uniqueidentifier not null ;
alter table SPMU_APPLICATION_STAGE_VALUE add STAGE_ID uniqueidentifier not null ;
