alter table SPMU_APPLICATION_OBJECT add constraint FK_SPMU_APPLICATION_OBJECT_ON_PARENT foreign key (PARENT_ID) references SPMU_APPLICATION_OBJECT(ID);
create index IDX_SPMU_APPLICATION_OBJECT_ON_PARENT on SPMU_APPLICATION_OBJECT (PARENT_ID);
