alter table SPMU_PLAN_SECTION add constraint FK_SPMU_PLAN_SECTION_ON_PARENT foreign key (PARENT_ID) references SPMU_PLAN_SECTION(ID);
alter table SPMU_PLAN_SECTION add constraint FK_SPMU_PLAN_SECTION_ON_TYPE foreign key (TYPE_ID) references SPMU_PLAN_TYPE(ID);
alter table SPMU_PLAN_SECTION add constraint FK_SPMU_PLAN_SECTION_ON_CREATOR foreign key (CREATOR_ID) references SEC_USER(ID);
create index IDX_SPMU_PLAN_SECTION_ON_PARENT on SPMU_PLAN_SECTION (PARENT_ID);
create index IDX_SPMU_PLAN_SECTION_ON_TYPE on SPMU_PLAN_SECTION (TYPE_ID);
create index IDX_SPMU_PLAN_SECTION_ON_CREATOR on SPMU_PLAN_SECTION (CREATOR_ID);
