exec sp_rename 'SPMU_PLAN_ACCOUNT.PLAN_ARTICLE_ID', 'PLAN_ARTICLE_ID__U76238', 'COLUMN' ^
exec sp_rename 'SPMU_PLAN_ACCOUNT.DIVISION_ID', 'DIVISION_ID__U60411', 'COLUMN' ^
exec sp_rename 'SPMU_PLAN_ACCOUNT.STATUS', 'STATUS__U34118', 'COLUMN' ^
exec sp_rename 'SPMU_PLAN_ACCOUNT.PROOF', 'PROOF__U68297', 'COLUMN' ^
exec sp_rename 'SPMU_PLAN_ACCOUNT.ASSIGNMENT', 'ASSIGNMENT__U69025', 'COLUMN' ^
exec sp_rename 'SPMU_PLAN_ACCOUNT.LAYOUT', 'LAYOUT__U43538', 'COLUMN' ^
exec sp_rename 'SPMU_PLAN_ACCOUNT.ORDER_', 'ORDER___U07642', 'COLUMN' ^
