alter table SPMU_COEFFICIENT add constraint FK_SPMU_COEFFICIENT_ON_MEASURE foreign key (MEASURE_ID) references SPMU_MEASURE(ID);
create index IDX_SPMU_COEFFICIENT_ON_MEASURE on SPMU_COEFFICIENT (MEASURE_ID);
