alter table SPMU_APPLICATION_OBJECT add constraint FK_SPMU_APPLICATION_OBJECT_ON_DIVISION foreign key (DIVISION_ID) references SPMU_DIVISION(ID) on delete CASCADE;
create index IDX_SPMU_APPLICATION_OBJECT_ON_DIVISION on SPMU_APPLICATION_OBJECT (DIVISION_ID);
