exec sp_rename 'SPMU_APPLICATION_STAGE_VALUE.STAGE_ID', 'STAGE_ID__U45058', 'COLUMN' ^
alter table SPMU_APPLICATION_STAGE_VALUE alter column STAGE_ID__U45058 uniqueidentifier  ;
drop index IDX_SPMU_APPLICATION_STAGE_VALUE_ON_STAGE on SPMU_APPLICATION_STAGE_VALUE ;
alter table SPMU_APPLICATION_STAGE_VALUE drop constraint FK_SPMU_APPLICATION_STAGE_VALUE_ON_STAGE ;
