alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_PLAN foreign key (PLAN_ID) references SPMU_PLAN_TYPE(ID);
create index IDX_SPMU_APPLICATION_STAGE_ON_PLAN on SPMU_APPLICATION_STAGE (PLAN_ID);
