alter table SPMU_APPLICATION add constraint FK_SPMU_APPLICATION_ON_PLAN_ARTICLE foreign key (PLAN_ARTICLE_ID) references SPMU_PLAN_ARTICLE(ID);
create index IDX_SPMU_APPLICATION_ON_PLAN_ARTICLE on SPMU_APPLICATION (PLAN_ARTICLE_ID);
