alter table SPMU_APPLICATION add constraint FK_SPMU_APPLICATION_ON_RESPONSIBLE foreign key (RESPONSIBLE_ID) references SPMU_EMPLOYEE(ID) on delete CASCADE;
create index IDX_SPMU_APPLICATION_ON_RESPONSIBLE on SPMU_APPLICATION (RESPONSIBLE_ID);
