sp_rename 'SPMU_EMPLOYEE', 'SPMU_EMPLOYEE__U96495' ;
alter table SEC_USER drop constraint FK_SEC_USER_ON_EMPLOYEE ;
alter table SPMU_APPLICATION drop constraint FK_SPMU_APPLICATION_ON_RESPONSIBLE ;
alter table SPMU_APPLICATION_RESPONSIBLE drop constraint FK_SPMU_APPLICATION_RESPONSIBLE_ON_EMPLOYEE ;
