sp_rename 'SPMU_DIVISION', 'SPMU_DIVISION__U93601' ;
alter table SPMU_APPLICATION_OBJECT drop constraint FK_SPMU_APPLICATION_OBJECT_ON_DIVISION ;
alter table SPMU_DIVISION drop constraint FK_SPMU_DIVISION_ON_PARENT ;
