alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_PARENT foreign key (PARENT_ID) references SPMU_APPLICATION_STAGE(ID);
create index IDX_SPMU_APPLICATION_STAGE_ON_PARENT on SPMU_APPLICATION_STAGE (PARENT_ID);
