sp_rename 'SPMU_AFFILATE', 'SPMU_AFFILATE__U80086' ;
alter table SEC_USER drop constraint FK_SEC_USER_ON_AFFILIATE ;
alter table SPMU_AFFILATE drop constraint FK_SPMU_AFFILATE_ON_PARENT ;
alter table SPMU_ANO drop constraint FK_SPMU_ANO_ON_AFFILIATE ;
alter table SPMU_APPLICATION drop constraint FK_SPMU_APPLICATION_ON_AFFILIATE ;
alter table SPMU_APPLICATION_OBJECT drop constraint FK_SPMU_APPLICATION_OBJECT_ON_AFFILIATE ;
alter table SPMU_APPLICATION_STAGE drop constraint FK_SPMU_APPLICATION_STAGE_ON_AFFILIATE ;
alter table SPMU_DIVISION drop constraint FK_SPMU_DIVISION_ON_AFFILIATE ;
