alter table SPMU_CONTRACT_STAGE add constraint FK_SPMU_CONTRACT_STAGE_ON_CONTRACT foreign key (CONTRACT_ID) references SPMU_CONTRACT(ID);
create index IDX_SPMU_CONTRACT_STAGE_ON_CONTRACT on SPMU_CONTRACT_STAGE (CONTRACT_ID);
