alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_SECTION foreign key (SECTION_ID) references SPMU_PLAN_SECTION(ID);
create index IDX_SPMU_APPLICATION_STAGE_ON_SECTION on SPMU_APPLICATION_STAGE (SECTION_ID);
