sp_rename 'SPMU_PLAN_ARTICLE', 'SPMU_PLAN_ARTICLE__U38436' ;
alter table SPMU_APPLICATION drop constraint FK_SPMU_APPLICATION_ON_ARTICLE ;
alter table SPMU_APPLICATION drop constraint FK_SPMU_APPLICATION_ON_PLAN_ARTICLE ;
alter table SPMU_APPLICATION_STAGE drop constraint FK_SPMU_APPLICATION_STAGE_ON_PLAN_ARTICLE ;
alter table SPMU_APPLICATION_STAGE_VALUE drop constraint FK_SPMU_APPLICATION_STAGE_VALUE_ON_ARTICLE ;
alter table SPMU_PLAN_ACCOUNT drop constraint FK_SPMU_PLAN_ACCOUNT_ON_ARTICLE ;
alter table SPMU_PLAN_ARTICLE drop constraint FK_SPMU_PLAN_ARTICLE_ON_PARENT ;
