sp_rename 'SPMU_PLAN_SECTION', 'SPMU_PLAN_SECTION__U98452' ;
alter table SPMU_APPLICATION_STAGE drop constraint FK_SPMU_APPLICATION_STAGE_ON_SECTION ;
alter table SPMU_PLAN_SECTION drop constraint FK_SPMU_PLAN_SECTION_ON_PARENT ;
