create table SPMU_APPLICATION_STAGE (
    ID uniqueidentifier,
    --
    PARENT_ID uniqueidentifier,
    NAME varchar(255) not null,
    DESCRIPTION varchar(255),
    ORDER_ integer,
    AFFILIATE_ID uniqueidentifier,
    OBJECT_ID uniqueidentifier not null,
    TYPE_ID uniqueidentifier,
    PLAN_ID uniqueidentifier,
    SECTION_ID uniqueidentifier,
    VALUE_ double precision,
    START_ datetime2,
    END_ datetime2,
    APPLICATION_ID uniqueidentifier not null,
    TASK_ uniqueidentifier,
    EDIT_NEEDED tinyint,
    IS_GGE tinyint,
    GGE_DET varchar(255),
    IS_PSD tinyint,
    PSD_DET varchar(255),
    STATUS integer,
    Q1 double precision,
    Q2 double precision,
    Q3 double precision,
    Q4 double precision,
    M1 double precision,
    M2 double precision,
    M3 double precision,
    M4 double precision,
    M5 double precision,
    M6 double precision,
    M7 double precision,
    M8 double precision,
    M9 double precision,
    M10 double precision,
    M11 double precision,
    M12 double precision,
    --
    primary key nonclustered (ID)
);