alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_OBJECT foreign key (OBJECT_ID) references SPMU_APPLICATION_OBJECT(ID);
create index IDX_SPMU_APPLICATION_STAGE_ON_OBJECT on SPMU_APPLICATION_STAGE (OBJECT_ID);
