alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_TYPE foreign key (TYPE_ID) references SPMU_APPLICATION_STAGE_TYPE(ID);
create index IDX_SPMU_APPLICATION_STAGE_ON_TYPE on SPMU_APPLICATION_STAGE (TYPE_ID);
