sp_rename 'SPMU_MEASURE', 'SPMU_MEASURE__U57668' ;
alter table SPMU_APPLICATION_STAGE_VALUE drop constraint FK_SPMU_APPLICATION_STAGE_VALUE_ON_MEASURE ;
alter table SPMU_COEFFICIENT drop constraint FK_SPMU_COEFFICIENT_ON_MEASURE ;
