alter table SPMU_APPLICATION add constraint FK_SPMU_APPLICATION_ON_ANALYTICA foreign key (ANALYTICA_ID) references SPMU_ACCOUNT(ID);
create index IDX_SPMU_APPLICATION_ON_ANALYTICA on SPMU_APPLICATION (ANALYTICA_ID);
