alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_ANALYTICA foreign key (ANALYTICA_ID) references SPMU_ACCOUNT(ID);
create index IDX_SPMU_APPLICATION_STAGE_ON_ANALYTICA on SPMU_APPLICATION_STAGE (ANALYTICA_ID);
