alter table SPMU_REGISTRY_CONTENT add constraint FK_SPMU_REGISTRY_CONTENT_ON_REGISTRY foreign key (REGISTRY_ID) references SPMU_REGISTRY(ID);
alter table SPMU_REGISTRY_CONTENT add constraint FK_SPMU_REGISTRY_CONTENT_ON_APPLICATION foreign key (APPLICATION_ID) references SPMU_APPLICATION(ID);
create index IDX_SPMU_REGISTRY_CONTENT_ON_REGISTRY on SPMU_REGISTRY_CONTENT (REGISTRY_ID);
create index IDX_SPMU_REGISTRY_CONTENT_ON_APPLICATION on SPMU_REGISTRY_CONTENT (APPLICATION_ID);
