alter table SPMU_EMPLOYEE add constraint FK_SPMU_EMPLOYEE_ON_POSITION foreign key (POSITION_ID) references SPMU_POSITION(ID);
create index IDX_SPMU_EMPLOYEE_ON_POSITION on SPMU_EMPLOYEE (POSITION_ID);
