alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_LOCATION foreign key (LOCATION_ID) references SPMU_LOCATION(ID);
create index IDX_SPMU_APPLICATION_STAGE_ON_LOCATION on SPMU_APPLICATION_STAGE (LOCATION_ID);
