alter table SPMU_EQUIPMENT_OBJECT add constraint FK_SPMU_EQUIPMENT_OBJECT_ON_PARENT foreign key (PARENT_ID) references SPMU_EQUIPMENT_OBJECT(ID);
alter table SPMU_EQUIPMENT_OBJECT add constraint FK_SPMU_EQUIPMENT_OBJECT_ON_AFFILATE foreign key (AFFILATE_ID) references SPMU_AFFILATE(ID);
alter table SPMU_EQUIPMENT_OBJECT add constraint FK_SPMU_EQUIPMENT_OBJECT_ON_DIVISION foreign key (DIVISION_ID) references SPMU_DIVISION(ID);
alter table SPMU_EQUIPMENT_OBJECT add constraint FK_SPMU_EQUIPMENT_OBJECT_ON_LOCATION foreign key (LOCATION_ID) references SPMU_LOCATION(ID);
create index IDX_SPMU_EQUIPMENT_OBJECT_ON_PARENT on SPMU_EQUIPMENT_OBJECT (PARENT_ID);
create index IDX_SPMU_EQUIPMENT_OBJECT_ON_AFFILATE on SPMU_EQUIPMENT_OBJECT (AFFILATE_ID);
create index IDX_SPMU_EQUIPMENT_OBJECT_ON_DIVISION on SPMU_EQUIPMENT_OBJECT (DIVISION_ID);
create index IDX_SPMU_EQUIPMENT_OBJECT_ON_LOCATION on SPMU_EQUIPMENT_OBJECT (LOCATION_ID);
