exec sp_rename 'SPMU_APPLICATION_LINK.CHILD_ID', 'CHILD_ID__U42415', 'COLUMN' ^
alter table SPMU_APPLICATION_LINK drop constraint FK_SPMU_APPLICATION_LINK_ON_CHILD ;
drop index IDX_SPMU_APPLICATION_LINK_ON_CHILD on SPMU_APPLICATION_LINK ;
