alter table SPMU_APPLICATION_STAGE add constraint FK_SPMU_APPLICATION_STAGE_ON_PRIORITY foreign key (PRIORITY_ID) references SPMU_PRIORITY(ID);
create index IDX_SPMU_APPLICATION_STAGE_ON_PRIORITY on SPMU_APPLICATION_STAGE (PRIORITY_ID);
