alter table SPMU_PLAN_VARIANT add constraint FK_SPMU_PLAN_VARIANT_ON_RESPONSIBLE foreign key (RESPONSIBLE_ID) references SPMU_EMPLOYEE(ID);
create index IDX_SPMU_PLAN_VARIANT_ON_RESPONSIBLE on SPMU_PLAN_VARIANT (RESPONSIBLE_ID);
